name: Excavator

on:
  schedule:
    - cron: '0 */12 * * *'   # ogni 12 ore
  workflow_dispatch:

permissions:
  contents: write

jobs:
  excavate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
